collective/easyform/profiles/default/actions.xml
collective/easyform/tests/attachment.txt
collective/easyform/tests/browser.txt

As documented in http://docs.plone.org/develop/plone/functionality/expressions.html?highlight=object_url#check-if-object-implements-an-interface

Fix Plone 5 actions

---

CHANGES.rst
collective/easyform/interfaces/mailer.py

...so it gets properly validated.

Change recipient address field to Email type

---

CHANGES.rst
collective/easyform/actions.py

(also see discussion in https://github.com/collective/collective.easyform/pull/34)

Possible fix for missing mail address from registry #33

---

CHANGES.rst
README.rst

- Add links to AT and DX
- Add link to PFG
- Add link to pypi
- Update link to GitHub Collective
- Update install part
- Fix header [rst]
- Adjust line-length and sentences

Update: README

---

CHANGES.rst
buildout.cfg
setup.py
src/collective/easyform/actions.py
src/collective/easyform/default_schemata/mail_body_default.pt
src/collective/easyform/interfaces/mailer.py
src/collective/easyform/tests/attachment.rst

fixes https://github.com/collective/collective.easyform/issues/56

Fix line breaks in mailer

---

CHANGES.rst
setup.py

closes https://github.com/collective/collective.easyform/issues/80

Added Products.validation dependency to make it work for archetypes-free sites.

---

CHANGES.rst
src/collective/easyform/browser/saveddata.pt
src/collective/easyform/tests/attachment.rst

Can not access saved data if action is called 'data'

---

CHANGES.rst
README.rst
docs/INSTALL.txt
docs/LICENSE.GPL
docs/LICENSE.txt
src/collective/easyform/__init__.py
src/collective/easyform/actions.py
src/collective/easyform/api.py
src/collective/easyform/browser/controlpanel.py
src/collective/easyform/browser/view.py
src/collective/easyform/configure.zcml
src/collective/easyform/interfaces/__init__.py
src/collective/easyform/interfaces/actions.py
src/collective/easyform/interfaces/customscript.py
src/collective/easyform/interfaces/easyform.py
src/collective/easyform/interfaces/fields.py
src/collective/easyform/interfaces/mailer.py
src/collective/easyform/interfaces/savedata.py
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/profiles/default/registry.xml
src/collective/easyform/vocabularies.py
src/collective/easyform/vocabularies.zcml

Fix for #91: Support showAll and includeEmpties also for the thanks page.

---

README.rst

as per https://github.com/collective/collective.easyform/issues/102

tweak 5.x version compatibility

---

CHANGES.rst
src/collective/easyform/configure.zcml
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/profiles/default/registry.xml

https://github.com/collective/collective.easyform/issues/94

Remove ProtectedEmail and ProtectedTextLine  as addable fields

---

CHANGES.rst
src/collective/easyform/browser/view.py
src/collective/easyform/exportimport.py
src/collective/easyform/interfaces/easyform.py
src/collective/easyform/interfaces/fields.py
src/collective/easyform/tests/fixtures/hidden_form.xml
src/collective/easyform/tests/fixtures/radio_form.xml
src/collective/easyform/tests/testThanksPage.py

This PR does 3 things:
- Support hidden fields in forms
- Fix broken field filtering on thanks page (introduced with 2.0.0b3)
- Add tests for thanks page

Support for hidden fields

---

CHANGES.rst
src/collective/easyform/browser/configure.zcml
src/collective/easyform/browser/view.py
src/collective/easyform/tests/testSaver.py

add @@get_save_data_adapters view

---

buildout.cfg
src/collective/easyform/actions.py
src/collective/easyform/tests/testMailer.py

fix unicode in xml mailer

---

src/collective/easyform/browser/easyform_layout.pt
src/collective/easyform/browser/view.py
src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po
src/collective/easyform/tests/robot/keywords.robot
src/collective/easyform/tests/robot/test_headerinjection.robot

Implement header injection

---

CHANGES.rst
src/collective/easyform/browser/easyform.css
src/collective/easyform/profiles/default/registry.xml

fixes https://github.com/collective/collective.easyform/issues/7

Icon for folder contents

---

CHANGES.rst
src/collective/easyform/profiles/default/types/EasyForm.xml

Moved from dotted to named behaviors.

---

CHANGES.rst
collective/easyform/browser/easyform_layout.pt
collective/easyform/browser/view.py

 Add missing ``header_injection`` implementation.

---

CHANGES.rst
collective/easyform/browser/view.py
collective/easyform/fields.py
collective/easyform/fields.zcml

These fields are not in the default fieldset

Validate fieldset fields

---

CHANGES.rst
src/collective/easyform/interfaces/mailer.py

Avoid potential CannotGetPortalError on startup

---

CHANGES.rst
src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/pt_BR/LC_MESSAGES/plone.po

Implements Brazilian Portuguese translation

---

CHANGES.rst
src/collective/easyform/browser/easyform_layout.pt
src/collective/easyform/browser/view.py

Forward port "E-mail adress invalid" translation and add css class to thankspage template.

Forward ports from 1.x branch

---

.travis.yml
CHANGES.rst
src/collective/easyform/browser/actions.py
src/collective/easyform/browser/view.py
tests-5.0.x.cfg

addresses https://github.com/collective/collective.easyform/issues/175

WIP: Fix data download

---

CHANGES.rst
src/collective/easyform/browser/actions.py

Remove hardcoded download button label check.

---

CHANGES.rst
setup.py
src/collective/easyform/configure.zcml
src/collective/easyform/migration/actions.py
src/collective/easyform/migration/configure.zcml
src/collective/easyform/migration/data.py
src/collective/easyform/migration/fields.py
src/collective/easyform/migration/pfg.py
tests-5.1.x.cfg

Changes by @buchi 
I'm just opening this PR to not forget about this branch and discuss about it.
@buchi - It looks conceptionally good to me. Did you successfully run a migration from PFG?

PFG migration

---

news/224.feature
news/225.bugfix
src/collective/easyform/browser/actions.py
src/collective/easyform/interfaces/actions.py
src/collective/easyform/permissions.zcml
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/profiles/default/rolemap.xml
src/collective/easyform/upgrades/1006.zcml
src/collective/easyform/upgrades/configure.zcml

Discussion: https://github.com/collective/collective.easyform/pull/222#discussion_r435513323

Make Actions better compatible with plone.supermodel/autoform directives

---

news/227.feature
news/228.feature
src/collective/easyform/browser/easyform.css
src/collective/easyform/interfaces/easyform.py
src/collective/easyform/interfaces/mailer.py
src/collective/easyform/locales/collective.easyform.pot
src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po
src/collective/easyform/tests/robot/keywords.robot

Make the fields editor look nicer.

---

.travis.yml
news/235.bugfix
src/collective/easyform/fields.py
tests-5.0.x.cfg
tests-5.1.x.cfg
tests-5.2.x.cfg

fixes #235

---

src/collective/easyform/actions.py
src/collective/easyform/browser/view.py
src/collective/easyform/config.py
src/collective/easyform/interfaces/__init__.py
src/collective/easyform/tests/action_errors.rst

see discussion at pull request #238

improve FORM_ERROR_MARKER to better match PFG

---

news/8.bugfix
src/collective/easyform/api.py
src/collective/easyform/tests/testApi.py

Fixes https://github.com/collective/collective.easyform/issues/8.

Make sure the catalog is updated after setting fields or actions.

---

news/3209.bugfix
src/collective/easyform/browser/fields.py

This solves an XML vulnerability.
See https://github.com/plone/Products.CMFPlone/issues/3209

In the field xml editor do not resolve entitities, and remove processing instructions

---

.travis.yml
buildout.cfg
news/3209.bugfix
src/collective/easyform/browser/fields.py
tests-5.0.x.cfg
tests-5.1.x.cfg

See https://github.com/plone/Products.CMFPlone/issues/3209
Backport of #254 to branch 2.x.

Field xml editor: do not resolve entitities [2.x]

---

CHANGES.rst
collective/easyform/browser/fields.py

See https://github.com/plone/Products.CMFPlone/issues/3209
Backport of #254 to branch 1.x.

Field xml editor: do not resolve entitities [1.x]

---

news/173.bugfix
src/collective/easyform/browser/easyform.css
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/profiles/default/registry.xml
src/collective/easyform/upgrades/1008.zcml
src/collective/easyform/upgrades/__init__.py
src/collective/easyform/upgrades/configure.zcml

In tabbed mode, they are hidden by autotoc pattern
This refs #173

Always display fieldsets legends

---

src/collective/easyform/locales/nl/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/nl/LC_MESSAGES/plone.po

Added Dutch translations for collective.easyform

Dutch translations

---

CHANGES.rst
README.rst
setup.py
src/collective/easyform/actions.py
src/collective/easyform/config.py
src/collective/easyform/locales/collective.easyform.pot
src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/ja/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/nl/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po
src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po
src/collective/easyform/tests/testSaver.py
src/collective/easyform/vocabularies.py
tests-5.0.x.cfg
tests-5.1.x.cfg
tests-5.2.x.cfg

This feature was first implemented for the 2.x branch: https://github.com/collective/collective.easyform/pull/283

Implement option to download the saved data as XLSX [master branch]

---

CHANGES.rst
src/collective/easyform/fields.py
src/collective/easyform/tests/testValidators.py
src/collective/easyform/validators.py

This fixes the same issue as for the 2.x branch: https://github.com/collective/collective.easyform/pull/282

Fix translation of validation errors [master branch].

---

.travis.yml
CHANGES.rst
buildout.cfg
collective/easyform/configure.zcml
collective/easyform/migration/actions.py
collective/easyform/migration/configure.zcml
collective/easyform/migration/data.py
collective/easyform/migration/fields.py
collective/easyform/migration/pfg.py

I made the fixes suggested by @mauritsvanrees on @thomasmassmann branch.
IOW, this could override #278

Backport PloneFormGen migration to 1.x (with changes)

---

requirements.txt
src/collective/easyform/migration/actions.py
src/collective/easyform/migration/fields.py
src/collective/easyform/migration/pfg.py
tests-5.0.x.cfg
tests-5.1.x.cfg
tests-5.2.x.cfg

Suggesting to forward port some changes made while using 1.x
Tests do pass for 5.0.x and 5.1.x and fail for 5.2.x (same failures as on `2.x` branch).

Forward some changes from 1.0.0 to 2.x

---

requirements.txt
src/collective/easyform/migration/actions.py
src/collective/easyform/migration/fields.py
src/collective/easyform/migration/pfg.py
tests-5.0.x.cfg
tests-5.1.x.cfg
tests-5.2.x.cfg

Suggesting to forward port some changes made while using 1.x
Tests do not pass for 5.0.x and 5.1.x and 5.2.x (but with same failures and errors as on `master` branch).

Forward some changes from 1.0.0 to master

---

src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po

Add some italian translation

---

CHANGES.rst
src/collective/easyform/actions.py

fixes SaveData Download bug for RichTextValue #288

bugfix #288

---

news/328.feature
src/collective/easyform/browser/view.py
src/collective/easyform/interfaces/easyform.py

Useful when you do (anonymous) form analytics and the analytics module picks up unique form id's in your site from the name attribute

Add field for name attribute

---

CHANGES.rst
src/collective/easyform/actions.py
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/upgrades/1011.zcml
src/collective/easyform/upgrades/__init__.py
src/collective/easyform/upgrades/configure.zcml

See https://github.com/collective/collective.easyform/issues/259

Fix persistence issue with SaveData storage

---

CHANGES.rst
src/collective/easyform/actions.py
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/upgrades/1011.zcml
src/collective/easyform/upgrades/__init__.py
src/collective/easyform/upgrades/configure.zcml

closes https://github.com/collective/collective.easyform/issues/259

Fix persistence issue with SaveData storage.

---

src/collective/easyform/interfaces/mailer.py
src/collective/easyform/locales/collective.easyform.pot

Adding an example (how to use replyto as Sender)

Example tales

---

.github/workflows/test.yml
CHANGES.rst
requirements.txt
src/collective/easyform/configure.zcml
src/collective/easyform/serializer.py
src/collective/easyform/tests/base.py
src/collective/easyform/tests/testSavedDataSerializer.py
src/collective/easyform/tests/testSaver.py

context: was not possible to migrate saved data
with collective.exportimport

restapi (de)serializers that include saved data

---

CHANGES.rst
src/collective/easyform/browser/fields_listing.pt

fixes gh-345
This PR requires that https://github.com/plone/plone.schemaeditor/pull/92 and https://github.com/plone/mockup/pull/1203 are merged

Modify the 'Form Fields' to work with latest schemaeditor

---

CHANGES.rst
src/collective/easyform/profiles/default/controlpanel.xml
src/collective/easyform/profiles/default/metadata.xml
src/collective/easyform/upgrades/1014.zcml
src/collective/easyform/upgrades/configure.zcml

Add an icon so the control panel would look nicer
This includes an upgrade step for existing installations

Add icon for the control panel tool

---

collective/easyform/browser/configure.zcml
collective/easyform/browser/likert.py
collective/easyform/browser/likert.zcml
collective/easyform/browser/likert_display.pt
collective/easyform/browser/likert_hidden.pt
collective/easyform/browser/likert_input.pt
collective/easyform/fields.py
collective/easyform/fields.zcml
collective/easyform/interfaces.py
collective/easyform/migration/actions.py
collective/easyform/migration/data.py
collective/easyform/migration/fields.py
collective/easyform/migration/pfg.py
collective/easyform/tests/testLikert.py

migration from ploneformgen to easyform.
- better logging
- thankyou page
- better error management

Migration features 1.x

---

CHANGES.rst
setup.py
src/collective/easyform/browser/likert_input.pt
src/collective/easyform/tests/testLikert.py

Fixes to Likert field

---

.github/workflows/test.yml
CHANGES.rst
collective/easyform/migration/fields.py

context: ReCaptcha fields may not be required in easyform

Migrate ReCaptcha field to not required (1.x)

---

.github/workflows/test.yml
CHANGES.rst
requirements.txt
setup.py
src/collective/easyform/browser/modeleditor.pt

use POST for XML modeleditor form
