CHANGES.rst, CONTRIBUTORS.rst, src/collective/easyform/actions.py
The current implementation was missing the recipient email address fallback for Plone 5. It was only implemented for the `from_address`.
The `ValueError` is still shown if there is no email address provided in the portal mail settings.
=> Use site email address if no recipient is specified

src/collective/easyform/default_schemata/fields_default.xml
Translate tags don't work for a non-english sites. With this tag, changing the Field label on languages other than english doesn't work. Tested on german Site and with plone.app.multilingual
=> removing i18 tags for initial fields

CHANGES.rst, CONTRIBUTORS.rst, src/collective/easyform/actions.py, src/collective/easyform/interfaces/mailer.py
I added a new checkbox in the mailer adapter settings' Message tab: "Send CSV data attachment" "Check this to send a CSV file attachment containing the values filled out in the form"
If it's checked, the submitted form data (as selected by the "Include All Fields" and "Show Responses" fields) are attached to the email in CSV format, with proper escaping of the comma delimiter and quote character.
=> New checkbox to send csv attachment of form data

CHANGES.rst, src/collective/easyform/configure.zcml, src/collective/easyform/profiles/default/actions.xml, src/collective/easyform/profiles/default/metadata.xml
Changed the permissions of the saveddata action.
Now the permissions of the action correspond to the permissions of the corresponding view.
=> Saveddata action permission

CHANGES.rst, requirements.txt, src/collective/easyform/actions.py, src/collective/easyform/api.py, src/collective/easyform/tests/testApi.py
The mailer action collects all available widgets and try to render them without some filtering.
Then, he filters the fields and get only the wanted fields.
When we use for example a captcha field, it will break when we try to render it, so i filtered also the widgets with only selected fields. In this case the mailer won't break.
=> Fix filtered widgets in mailer

.travis.yml, setup.py, src/collective/easyform/browser/view.py, tests-5.0.x.cfg
Please consider that 5.0.x is not that old and people have a lot of existing hosting based on it. Where its just a couple of lines to retain compatibility and the plugin itself is still buggy please can we make this small effort to keep it compatible until it is really is a good reason to stop support?
=> retain 5.0.x compatibility

CHANGES.rst, collective/easyform/browser/easyform_layout.pt, collective/easyform/browser/view.py
Needed on Plone 4, not on Plone 5.
See https://github.com/collective/collective.easyform/pull/167#issuecomment-495149499
Also fixed error when headerInjection field is None, which is the case for existing forms.
=> Fixed headerinjection by adding a macro. [1.x]

collective/easyform/api.py, collective/easyform/tests/attachment.txt, collective/easyform/tests/browser.txt, collective/easyform/tests/testCustomScript.py, collective/easyform/tests/testMailer.py, collective/easyform/tests/test_robot.py
Most of the tests failed for stupid reasons. They are fixed.
I am ignoring the robot tests, because half of them are failing because modals are not working. Fixing the modals would be better, but too much work for now. You get a warning message about this when running the tests.
Now Travis should finally be happy, which helps when we are finally doing some fixes to get 1.x working better on Plone 4.3. Still: use at your own risk.
=> Fix tests on 1.x

CHANGES.rst, src/collective/easyform/fields.py, src/collective/easyform/fields.zcml, src/collective/easyform/tests/fixtures/fieldset_with_single_field.xml, src/collective/easyform/tests/fixtures/single_field.xml, src/collective/easyform/tests/testValidators.py
This fixes #172 and #157 and probably #132 as well.
The validation fixes are forward ported from branch 1.x (PR #174).
The fixes for the default value are new, and the tests are new too.
=> Fix validation and defaults for fields in fieldsets.

CHANGES.rst, src/collective/easyform/api.py, src/collective/easyform/tests/testApi.py
This fixes the order on the default mailer template. This solves one part of issue #163 on master.
(Letting the thanks page use the correct order is trickier, and I am not going to try that now.)
This PR also adds tests for the `filter_fields` api function.
=> Let filter_fields return fields in the correct order. [master]

CHANGES.rst, collective/easyform/fields.py, collective/easyform/fields.zcml, collective/easyform/tests/fixtures/fieldset_with_single_field.xml, collective/easyform/tests/fixtures/single_field.xml, collective/easyform/tests/testValidators.py
Backport of part of PR #177. (The rest of 177 was actually a forward port from 1.x, so the two branches are even on that point, after merge).
Fixes #157 for 1.x.
=> Fixed defaults for fieldsets [1.x]

CHANGES.rst, README.rst, setup.py, src/collective/easyform/browser/fields.zcml, src/collective/easyform/browser/widgets.zcml, src/collective/easyform/fields.py, src/collective/easyform/interfaces/__init__.py, src/collective/easyform/interfaces/fields.py, src/collective/easyform/tests/base.py
Back from the graveyard, thanks to @1letter!
Based on https://github.com/collective/collective.easyform/pull/148, just a rebase and small fix.
Works on Plone 5.2 and Python 3. Needs collective.z3cform.norobots master checkout.
Fixes #145
=> Add collective.z3cform.norobots integration

CHANGES.rst, src/collective/easyform/tests/testValidators.py, src/collective/easyform/validators.py
In Relation to the issue #209.
Something similar happened on our instance using the isCommaSperatedEmail Field #202 
Today I think I found and fixed the problem.
Simply return if the value of the field is None.
If the field is set to be required the Required will take care of None Values.
=> fix validators for None

news/224.feature, news/225.bugfix, news/226.breaking, src/collective/easyform/browser/actions.py, src/collective/easyform/interfaces/actions.py, src/collective/easyform/permissions.zcml, src/collective/easyform/profiles/default/metadata.xml, src/collective/easyform/profiles/default/rolemap.xml, src/collective/easyform/upgrades/1006.zcml, src/collective/easyform/upgrades/configure.zcml
Hide the "description" field from form actions, as it is not used anywhere.
Customizations which try to omit or use the description field might need adaptions.
=> Hide description field from form actions.

news/227.feature, src/collective/easyform/interfaces/easyform.py, src/collective/easyform/interfaces/mailer.py, src/collective/easyform/locales/collective.easyform.pot, src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po, src/collective/easyform/tests/robot/keywords.robot
Simplify the editing UI: Introduce a new "Advanced" tab when creating a form for not so frequent used settings.
Change permissions to allow editors to define the recipient from form field values in addition to a fixed recipient.
Now it's looking like this:
Creating a form - default tab
Creating a form - advanced tab (these were previously all on the default tab)
Editing the mailer action - new field for users without manager rights
Editing the mailer action for admins
=> Simplify the editing UI

news/229.breaking, src/collective/easyform/config.py, src/collective/easyform/interfaces/easyform.py, src/collective/easyform/interfaces/fields.py, src/collective/easyform/interfaces/mailer.py, src/collective/easyform/permissions.zcml, src/collective/easyform/profiles/default/rolemap.xml
Change semantics for the "advanced" permission and introduce new "technical" permission.
To better support use cases for "power users" while not overloading them with complex fields where a technical understanding is necessary the permissions are changed as follows:
"Edit Advanced Fields":
- IEasyForm.submitLabel
- IEasyForm.useCancelButton
- IEasyForm.resetLabel
- IEasyForm.form_tabbing
- IEasyForm.default_fieldset_label
- IFieldExtender.field_widget
- IFieldExtender.validators
"Edit Technical Fields":
- IEasyForm.method
- IEasyForm.unload_protection
- IEasyForm.CSRFProtection
- IEasyForm.forceSSL
- IMailer.replyto_field
- IMailer.xinfo_headers
- IMailer.additional_headers
Note: no upgrade step provided because this will be covered by the upgrade step in this PR: …
=> Change semantics for the "advanced" permission and introduce new "technical" permission.

news/229.breaking, src/collective/easyform/interfaces/easyform.py
Allow non-privileged users to configure button labels. As these labels are not translated, you'd be stuck with whatever you get on form creation, even if changing the form's language afterwards.
=> Lower button labels permission

news/239.bugfix, src/collective/easyform/profiles/default/actions.xml
URLs in actions menu pointed to `form/actions/fields` if on `form/actions`. now fixed.
=> fix actions urls when on action or field traverser

news/219.bugfix, src/collective/easyform/browser/configure.zcml, src/collective/easyform/browser/easyform.css, src/collective/easyform/browser/view.py, src/collective/easyform/profiles/default/actions.xml, src/collective/easyform/profiles/default/metadata.xml, src/collective/easyform/tests/robot/keywords.robot, src/collective/easyform/tests/testMisc.py, src/collective/easyform/upgrades/1007.zcml, src/collective/easyform/upgrades/configure.zcml
See issue #219, issue #244, PR #239.
Includes upgrade step to apply the `actions.xml`.
Note that this adds a View link in the toolbar when you are within the Fields or Actions views, but it is at a different position than normally, because the normal position is only available for real content items.
The order is: Contents, Actions, View (followed by History and Sharing)
=> Fix action urls and tests.

src/collective/easyform/profiles/default/registry.xml, src/collective/easyform/tests/testSetup.py, src/collective/easyform/upgrades/1007.zcml, src/collective/easyform/upgrades/__init__.py
This replaces PR #248 in a much simpler way, now that I know more what I am doing.
This tries to not break on Plone 5.0, which does not have the `combine_bundles` function. We could also drop 5.0 support. But the tests *should* still pass.
=> Set last_compilation date and combine bundles

.travis.yml, news/252.bugfix, src/collective/easyform/fields.py, src/collective/easyform/tests/base.py, src/collective/easyform/tests/serverside_field.rst, src/collective/easyform/tests/testMailer.py, tests-5.2.3-pending.cfg, tests-5.2.x.cfg
See issue #252.
This does not fix anything, but it should show the errors on Travis.
=> Fix zope interface 5.1.x fieldset problem

CHANGES.rst, src/collective/easyform/interfaces/easyform.py
The translate method from zope.i18n needs the request as context
to determine the language.
After this change the labels actually get translated:
Before the english default value was returned.
=> Add missing "context" parameter to translate method for labels

CHANGES.rst, setup.py, src/collective/easyform/fields.py, src/collective/easyform/tests/testValidators.py, src/collective/easyform/validators.py
This PR fixes translations of validation errors.
All validators used from `Products.validation.validators` are passing ´kwargs` into `recursiveTranslate` from `Products.validation.i18n`, which checks for a "REQUEST" key and passes it to the translate method.
Thus this PR implements this and passes "REQUEST" if possible as additional kwarg.
I added a test to make sure translations are working now for validators, the local output seems fine:
```sh
> ./bin/test -t test_validator_translation
... truncated ...
Running collective.easyform.tests.base.collective.easyform:Integration tests:
Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
Set up plone.testing.zope.Startup in 0.179 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.180 seconds.
Set up …
```
=> Fix translation of validation errors.

CHANGES.rst, README.rst, setup.py, src/collective/easyform/actions.py, src/collective/easyform/config.py, src/collective/easyform/locales/collective.easyform.pot, src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po, src/collective/easyform/tests/testSaver.py, src/collective/easyform/vocabularies.py, tests-5.0.x.cfg, tests-5.1.x.cfg, tests-5.2.x.cfg
- Based on openpyxl
- Available as an extra (by default it's not available, nor is openpyxl required)
- I did a tiny refactoring to reuse gathering the header and row data
All data saver related tests are passing on my machine (including the newly added xlsx download test):
```
$ ./bin/test -t testSaver
...
truncated
...
Running collective.easyform.tests.base.collective.easyform:Integration tests:
Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
Set up plone.testing.zope.Startup in 0.243 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.177 seconds.
Set up plone.app.event.testing.PAEventLayer in 0.171 seconds.
Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.093 seconds.
Set up collective.easyform.tests.base.Fixture …
```
=> Implement option to download the saved data as XLSX

src/collective/easyform/actions.py, src/collective/easyform/tests/fixtures/fieldset_multiple_choice.xml, src/collective/easyform/tests/testSaver.py
This PR re-uses the `serialize` method introduced in the `mailer` action for the xlsx data saver (resp. downloader).
I notised that especially list types are not working. 
Tests of `testSaver` and `testMailer` are passing running with python 2.7.18 and python 3.8.6
I did not add a new changlog entry since this fix belongs to the not yet released feature "Download XLSX version of saved data"
=> Saving certain data types caused issues writing them into a xlsx cell.

.travis.yml, CHANGES.rst, buildout.cfg, collective/easyform/configure.zcml, collective/easyform/migration/actions.py, collective/easyform/migration/configure.zcml, collective/easyform/migration/data.py, collective/easyform/migration/fields.py, collective/easyform/migration/pfg.py
Uses the existing migration and adjusts some imports and method calls to be compatible with 1.x.
It also sets the correct description for fieldsets (needs to be an attribute, not a property).
=> Backport PloneFormGen migration to 1.x

CHANGES.rst, src/collective/easyform/browser/actions.zcml, src/collective/easyform/profiles/default/actions.xml, src/collective/easyform/profiles/default/metadata.xml, src/collective/easyform/tests/testSaver.py, src/collective/easyform/upgrades/1012.zcml, src/collective/easyform/upgrades/__init__.py, src/collective/easyform/upgrades/configure.zcml
`collective.easyform.DownloadSavedInput` is set by default for Owner, Manager and Site Administrator roles
This refs #357
=> Use specific permission for displaying/downloading saved data

CHANGES.rst, src/collective/easyform/browser/actions.py, src/collective/easyform/browser/fields.py
* No need for the "Unload protection"
* When clicking the button "Done" at the bottom, send the editor back to the form, instead of remaining in the "Form fields"
* When clicking the button "Save" at the bottom, send the editor back to the form, instead of remaining in the "Edit actions"
=> Few UX improvements

CHANGES.rst, src/collective/easyform/actions.py, src/collective/easyform/tests/testSaver.py
This makes the for example multiple choice fields in Excel/Spreadsheets
way more controllable.
Example
=> Use "|" as delimiter of list types in exports. (4.x)

CHANGES.rst, src/collective/easyform/actions.py, src/collective/easyform/tests/testSaver.py
This makes the for example multiple choice fields in Excel/Spreadsheets
way more controllable.
Example:
=> Use "|" as delimiter of list types in exports. (3.x)

CHANGES.rst, setup.py, src/collective/easyform/browser/view.py
This cherry-picks three commits from PR #374 by @petschki.
That PR has too many conflicting files now, due to introducing mxdev (and a 300 line Makefile which I am still not a fan of) and doing black/isort. This could be retried in a separate PR. The tests pass locally.
Fixes issue #370.
=> Fix IEasyFormWidget marker for GroupForm widgets (take 2)

CHANGES.rst, src/collective/easyform/profiles/default/actions.xml, src/collective/easyform/profiles/default/metadata.xml, src/collective/easyform/setuphandlers.py, src/collective/easyform/upgrades/1016.zcml, src/collective/easyform/upgrades/configure.zcml, src/collective/easyform/upgrades/profiles/1016/actions.xml, src/collective/easyform/upgrades/profiles/1016/registry.xml
In the actions dropdown, before:
after:
Includes upgrade step.
Also, a content type icon was added by @frapell last year in commit 11f5ba4b64a92fd2bfa0cc4e33c2ce0d68ff53c4, but there was no upgrade step.  I added it here.  See comments in that commit for why this icon would ideally not be needed, and Plone should reuse the FTI icon instead.  But currently it still is needed, so let's have an upgrade step.
=> Add icon expressions

CHANGES.rst, src/collective/easyform/browser/configure.zcml
context: the contents link in the toolbar from saveddata view was broken
This issue was already discussed and solved [here](https://github.com/collective/collective.easyform/issues/219): but the folder_contents link was broken for  the saveddata view
Note: there is already a fix for broken tests included in https://github.com/collective/collective.easyform/pull/407
=> folder_contents accessible from saveddata

CHANGES.rst, src/collective/easyform/migration/fields.py, src/collective/easyform/tests/testValidators.py
context: ReCaptcha fields may not be required in easyform
=> Migrate ReCaptcha field to not required

CHANGES.rst, src/collective/easyform/browser/controlpanel.py, src/collective/easyform/browser/fields.py, src/collective/easyform/fields.zcml, src/collective/easyform/locales/collective.easyform.pot, src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/fr/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/ja/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/nl/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po, src/collective/easyform/profiles/default/metadata.xml, src/collective/easyform/profiles/default/registry.xml, src/collective/easyform/upgrades/1017.zcml, src/collective/easyform/upgrades/configure.zcml, src/collective/easyform/upgrades/profiles/1017/registry.xml, src/collective/easyform/validators.py
add the option to set a max filesize to upload in a form
=> Max fileupload

news/279.bugfix, src/collective/easyform/migration/fields.py
This fixes #279 for the 2.x version
=> Set fieldset description as attribute, not node, when migrating from PFG (2.x)

news/279.bugfix, src/collective/easyform/migration/fields.py
This fixes #279 
Obsoletes: https://github.com/collective/collective.easyform/pull/280
I made this fork in order to be able to rebase and force-push and merge, which I cannot do on thomas' branch.
=> fix(ISSUE-279): :bug: set fieldset description as attribute, not node, when migrating from PFG

CHANGES.rst, src/collective/easyform/profiles/default/types/EasyForm.xml, src/collective/easyform/upgrades/1017.zcml, src/collective/easyform/upgrades/profiles/1017/types/EasyForm.xml
This behavior wasn't enabled by default for easyform. It makes sense to enable it, as this behavior is often enabled by default (e.g. plone.app.contenttypes)
=> enable changing shortname behavior

CHANGES.rst, src/collective/easyform/upgrades/__init__.py
When upgrading from Plone 5 to Plone 6, the upgrade broke with:
```
2024-10-08 13:18:11,350 INFO    [ftw.upgrade:177][waitress-0] ______________________________________________________________________
2024-10-08 13:18:11,351 INFO    [ftw.upgrade:178][waitress-0] UPGRADE STEP collective.easyform:default: Update last_compilation of bundle
2024-10-08 13:18:11,351 ERROR   [ftw.upgrade:39][waitress-0] FAILED
```
We're not using the `last_compilation` registry entry anymore, thankfully.
This PR fixes that by just ignoring the `last_compilation` update method in Plone 6.
=> Fix Plone 5 related upgrade steps in Plone 6.

src/collective/easyform/actions.py
Fix encoding problems when using umlauts in from or to headers.
=> Fix encoding for utf8 headers 3x

src/collective/easyform/browser/view.py
Solves #386 by backporting the fix from https://github.com/collective/collective.easyform/commit/3fa337b3ef0bc88707e8582cd1fbee4571077b9b to the 3.x branch
=> backport fix to 3.x branch

src/collective/easyform/browser/model_listing.pt, src/collective/easyform/browser/modeleditor.pt
The current `@@fields`, `@@actions` forms and the related modelleditor views fill the `content` slot of the master template, which is changed with Plone 6, see comment from `Products.CMFPlone`:
> Please note that this template fills the "content" slot instead of the "main" slot, this is done so we can provide stuff like the content tabs. This also means that we have to supply things that are normally present from main_template. [[source]](https://github.com/plone/Products.CMFPlone/blob/6.0.11/Products/CMFPlone/browser/templates/author.pt#L18-L23)
The `model_listing.pt` also inserts additional `#edit-bar` div and a duplicate portal message. See it on https://classic.demo.plone.org/ by creating an EasyForm, and opening the fields actions. A search for `#edit-bar` in the console will have …
=> Fix templates to match Plone 6 master template

CHANGES.rst, src/collective/easyform/browser/view.py, src/collective/easyform/interfaces/easyform.py, src/collective/easyform/locales/collective.easyform.pot, src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/fr/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/ja/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/nl/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po
Add a checkbox to disable autofocus on the first input. It is enabled by default as is the default in Dexterity forms so it should not break anything.
=> Add Advanced config to remove autofocus on firt input

CHANGES.rst, src/collective/easyform/browser/actions.py, src/collective/easyform/interfaces/savedata.py, src/collective/easyform/locales/collective.easyform.pot, src/collective/easyform/locales/de/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/en/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/es/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/eu/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/fr/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/it/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/ja/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/nl/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/pt_BR/LC_MESSAGES/collective.easyform.po, src/collective/easyform/locales/uk/LC_MESSAGES/collective.easyform.po, src/collective/easyform/tests/testSaver.py
On a client site I have a form with 12 questions and almost 700 entries and this takes over 40 seconds to load. Downloading the csv data takes just 4 seconds.
By default the page now uses a batch size of 10.
For good measure, you can override this by passing `?batch_size=x` in the url, but this gets lost when you use the batch navigation to go to the next page. This is because it is not supported by the standard `CrudBatchView` from `plone.z3cform`.
=> Use batching on the saved data page.
